apiVersion: apps/v1
kind: Deployment
metadata:
  name: zendrix-deployment
  labels:
    app: zendrix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zendrix
  template:
    metadata:
      labels:
        app: zendrix
    spec:
      containers:
      - name: zendrix
        image: jamessubair/zendrix-app
        ports:
        - containerPort: 85
