apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsevaluationquiz-deployment
  labels:
    app: devopsevaluationquiz-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devopsevaluationquiz-deployment
  template:
    metadata:
      labels:
        app: devopsevaluationquiz-deployment
    spec:
      containers:
      - name: devopsevaluationquiz-deployment
        image: jamessubair/project2
        ports:
        - containerPort: 85
