apiVersion: v1
kind: Service
metadata:
  name: devopsevaluationquiz-service
spec:
  type: NodePort
  selector:
    app: devopsevaluationquiz
  ports:
    - port: 85
      targetPort: 85
      nodePort: 30008
